// Palette check: computes WCAG 2.x contrast ratios for the UI's color tokens
// against the surfaces they sit on, and simulates color-vision deficiency
// (Machado et al. 2009, severity 1.0) to measure how far apart the chart
// series and the improved/regressed verdict colors stay (CIE76 ΔE in Lab).
// Usage: node scripts/palette-check.mjs   → writes docs/palette-report.{json,md}
import { readFileSync, writeFileSync } from 'node:fs';

const css = readFileSync(new URL('../web/src/styles.css', import.meta.url), 'utf8');
const root = css.slice(css.indexOf(':root'), css.indexOf('}', css.indexOf(':root')));
const tokens = Object.fromEntries([...root.matchAll(/--([\w-]+):\s*(#[0-9a-fA-F]{6})/g)].map((m) => [m[1], m[2]]));

const hexToRgb = (h) => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16) / 255);
const toLinear = (c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
const fromLinear = (c) => (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055);
const luminance = (rgb) => {
  const [r, g, b] = rgb.map(toLinear);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};
const contrast = (a, b) => {
  const [l1, l2] = [luminance(hexToRgb(a)), luminance(hexToRgb(b))].sort((x, y) => y - x);
  return (l1 + 0.05) / (l2 + 0.05);
};

// Machado, Oliveira & Fernandes (2009), severity 1.0, applied in linear RGB.
const CVD = {
  protanopia: [[0.152286, 1.052583, -0.204868], [0.114503, 0.786281, 0.099216], [-0.003882, -0.048116, 1.051998]],
  deuteranopia: [[0.367322, 0.860646, -0.227968], [0.280085, 0.672501, 0.047413], [-0.01182, 0.04294, 0.968881]],
  tritanopia: [[1.255528, -0.076749, -0.178779], [-0.078411, 0.930809, 0.147602], [0.004733, 0.691367, 0.3039]],
};
const simulate = (rgb, m) => {
  const lin = rgb.map(toLinear);
  return m.map((row) => fromLinear(Math.min(1, Math.max(0, row[0] * lin[0] + row[1] * lin[1] + row[2] * lin[2]))));
};
const toLab = (rgb) => {
  const [r, g, b] = rgb.map(toLinear);
  const xyz = [
    (0.4124 * r + 0.3576 * g + 0.1805 * b) / 0.95047,
    0.2126 * r + 0.7152 * g + 0.0722 * b,
    (0.0193 * r + 0.1192 * g + 0.9505 * b) / 1.08883,
  ].map((t) => (t > 216 / 24389 ? Math.cbrt(t) : (24389 / 27 * t + 16) / 116));
  return [116 * xyz[1] - 16, 500 * (xyz[0] - xyz[1]), 200 * (xyz[1] - xyz[2])];
};
const deltaE = (a, b) => Math.hypot(...toLab(a).map((v, i) => v - toLab(b)[i]));

const surfaces = ['bg', 'surface'];
const checks = [
  // Status colors are also used as text (badges, verdicts, errors), so they get the text threshold.
  ...['ink', 'ink-2', 'muted', 'good', 'serious', 'critical', 'warning'].map((t) => ({
    token: t,
    kind: 'text',
    min: 4.5,
    criterion: 'WCAG 1.4.3 AA text',
  })),
  ...['series-1', 'series-2', 'violet', 'aqua'].map((t) => ({
    token: t,
    kind: 'graphic/status',
    min: 3,
    criterion: 'WCAG 1.4.11 non-text (3:1)',
  })),
];
const contrastRows = checks.flatMap((c) =>
  surfaces.map((s) => {
    const ratio = contrast(tokens[c.token], tokens[s]);
    return { ...c, color: tokens[c.token], on: s, ratio: Math.round(ratio * 100) / 100, pass: ratio >= c.min };
  }),
);

const pairs = [
  ['series-1', 'series-2', 'tokens chart: input vs output'],
  ['good', 'serious', 'eval verdict: improved vs regressed'],
];
const cvdRows = pairs.map(([a, b, use]) => {
  const ra = hexToRgb(tokens[a]);
  const rb = hexToRgb(tokens[b]);
  const row = { pair: `${a} / ${b}`, use, normal: Math.round(deltaE(ra, rb) * 10) / 10 };
  for (const [name, m] of Object.entries(CVD)) row[name] = Math.round(deltaE(simulate(ra, m), simulate(rb, m)) * 10) / 10;
  return row;
});

writeFileSync(new URL('../docs/palette-report.json', import.meta.url), JSON.stringify({ tokens, contrast: contrastRows, cvd: cvdRows }, null, 2) + '\n');
const failing = contrastRows.filter((r) => !r.pass);
const md = [
  '# Palette report',
  '',
  'Generated by `node scripts/palette-check.mjs` from the `:root` tokens in `web/src/styles.css`.',
  '',
  `Contrast: **${contrastRows.length - failing.length}/${contrastRows.length}** token-on-surface pairs meet their WCAG 2.x threshold.`,
  '',
  '| Token | Color | On | Ratio | Needs | Pass |',
  '|---|---|---|---|---|---|',
  ...contrastRows.map((r) => `| \`--${r.token}\` | \`${r.color}\` | \`--${r.on}\` | ${r.ratio.toFixed(2)}:1 | ${r.min}:1 (${r.criterion}) | ${r.pass ? 'yes' : '**no**'} |`),
  '',
  '## Color-vision-deficiency separation (CIE76 ΔE, Machado 2009 severity 1.0)',
  '',
  'ΔE ≳ 10 is generally easy to tell apart; < 5 is hard. Simulation is an approximation, not a user study.',
  'Neither pair relies on color alone: the chart has a legend + tooltip, verdicts carry ▲/▼ and a word.',
  '',
  '| Pair | Used for | Normal | Protanopia | Deuteranopia | Tritanopia |',
  '|---|---|---|---|---|---|',
  ...cvdRows.map((r) => `| ${r.pair} | ${r.use} | ${r.normal} | ${r.protanopia} | ${r.deuteranopia} | ${r.tritanopia} |`),
  '',
].join('\n');
writeFileSync(new URL('../docs/palette-report.md', import.meta.url), md);
console.log(md);
